#ifndef uartConfig_H_
#define uartConfig_H_


#define ON  1
#define OFF  0

/*USER CAN CHOOSE ETHIER
-ASYNCHRONOUS
-SYNCHRONOUS
--------------------------*/
#define SYNCHRONIZATION ASYNCHRONOUS

/*USER CAN CHOOSE
-ONE_STOP_BIT
-TWO_STOP_BITS
*/
#define STOP_BITS      ONE_STOP_BIT

/*USER CAN CHOOSE CHARACTER SIZE
-FIVE_BITS
-SIX_BITS
-SEVEN_BITS
-EIGHT_BITS
-NINE_BITS
 */
#define CHARACTER_SIZE EIGHT_BITS

/*PARITY CHECK
 -PARITY_DISABLE
 -EVEN_PARITY
 -ODD_PARITY
 * */
#define PARITY_MODE PARITY_DISABLE

/*CLOCK POLATIRY- THIS IS ONLY FOR SYNCHRONOUS MODE
-TRANSIMT_ON_RISING
-TRANSIMT_ON_FALLING
-DISABLE_CLOCK
-HAS NO EFFECT IF ASYNCHRONOUS MODE
*/
#define CLOCK_POLARITY DISABLE_CLOCK


/*THIS MACRO CONTROLS RECEIVER ENABLE
-RECEIVER_EN
-RECEIVER_DIS
*/
#define RECEIVEING RECEIVER_EN

/*THIS MACRO CONTROLS TRANSMITTER ENABLE
-TRANSMITTER_EN
-TRANSMITTER_DIS
*/
#define TRANSMITTING TRANSMITTER_EN

/*SPEED
-NORMAL_SPEED
-DOUBLE_SPEED
 * */
#define SPEED NORMAL_SPEED

/*THIS MACRO CONTROLS NINE_BIT_DATA_FRAME
-ON
-OFF
 */
#define NINE_BIT OFF

/*THIS MACRRO CONTROLS THE BUAD RATE
-BT_2400BT_8MHz
-BT_4800_8MHz
-BT_9600_8MHz
-BT_14400_8MHz
-BT_19200_8MHz
-BT_28800_8MHz
-BT_38400_8MHz
-BT_57600_8MHz
-BT_76800_8MHz
 */

#define BUAD_RATE  BT_9600_8MHz








#endif /*uartConfig_H_*/
