
#ifndef ULTRASONIC_CONFIG_H_
#define ULTRASONIC_CONFIG_H_




#define ULTRASONIC_ECHO_PORT		DIO_PORTB
#define ULTRASONIC_ECHO_PIN			PIN_2
			   
			   
#define ULTRASONIC_Trigger_PORT	 	DIO_PORTB
#define ULTRASONIC_Trigger_PIN		PIN_0


#endif /* ULTRASONIC_CONFIG_H_ */

